columnSuffix: null
contentColumnType: string
fieldGroup: 261fcf20-0012-4add-b92a-93b20d10ab50 # Common
handle: image
instructions: null
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b1947b9f-bbb6-4312-92ca-cf2c8a503538' # Uploads Volume
  defaultUploadLocationSubpath: '@web/resources/uploads/{slug}'
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:b1947b9f-bbb6-4312-92ca-cf2c8a503538' # Uploads Volume
  restrictedLocationSubpath: '/web/resources/img/{slug}'
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:b1947b9f-bbb6-4312-92ca-cf2c8a503538' # Uploads Volume
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
