dateModified: 1677818117
email:
  fromEmail: pamrmont@gmail.com
  fromName: MOS
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    261fcf20-0012-4add-b92a-93b20d10ab50: Common # Common
    300ffcc4-0e22-44f0-b41b-f8bd0c279a8b: 'Display Date' # Display Date
    97210d52-cb67-43bd-bc5c-448c16038204: MOS # MOS
    50908657-7579-47f7-8187-6d789401aa3c: Updates # Updates
    bee12f3b-da05-4f13-8168-eb93d275e059: Signature # Signature
    c36f48d8-908b-4b76-b64b-9223c89b80cd: Writer # Writer
    c92ba992-cb54-4dfb-ae65-66757f29798b: 'MO''S' # MO'S
    c990a4f1-24e2-4d37-a050-f36e857917f0: Entry # Entry
    e9336d49-aff3-42df-ac64-8267c6b5e19d: Updates # Updates
system:
  edition: solo
  live: true
  name: MOS
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
