defaultPlacement: end
enableVersioning: true
handle: foodFAQs
name: 'Food FAQs'
propagationMethod: all
siteSettings:
  c92ba992-cb54-4dfb-ae65-66757f29798b: # MO'S
    enabledByDefault: true
    hasUrls: true
    template: static-page/_entry
    uriFormat: food-faqs
type: single
